-- MySQL Script generated by MySQL Workbench
-- 06/11/16 21:20:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema matproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matproject` ;
USE `matproject` ;

-- -----------------------------------------------------
-- Table `matproject`.`userrole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`userrole` (
  `urid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL,
  `key` VARCHAR(50) NULL,
  PRIMARY KEY (`urid`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  UNIQUE INDEX `urid_UNIQUE` (`urid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`users` (
  `uid` INT(9) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `JoiningData` VARCHAR(255) NULL,
  `PhoneNumber` VARCHAR(255) NULL,
  `profilePhoto` VARCHAR(255) NULL,
  `gender` INT(9) NULL,
  `PackageID` INT(9) NULL,
  `Profilestatus` VARCHAR(7) NULL,
  `userrole` INT(9) NULL,
  `isemailverified` TINYINT(1) NULL,
  `isActive` TINYINT(1) NULL,
  `isDelete` TINYINT(1) NULL,
  `deleteby` INT(9) NULL,
  PRIMARY KEY (`uid`),
  INDEX `idx_actor_last_name` (`password` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_user role1_idx` (`userrole` ASC),
  CONSTRAINT `fk_user_user role1`
    FOREIGN KEY (`userrole`)
    REFERENCES `matproject`.`userrole` (`urid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `matproject`.`userprofile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`userprofile` (
  `upid` INT(9) NOT NULL AUTO_INCREMENT,
  `uid` INT(9) NOT NULL,
  `dob` VARCHAR(255) NULL,
  `profileImages` LONGTEXT NULL,
  `interestedIn` VARCHAR(255) NULL,
  `religion` INT(9) NULL,
  `sect` INT(9) NULL,
  `languages` VARCHAR(255) NULL,
  `motherTongue` INT(9) NULL,
  `livingIn_Country` INT(9) NULL,
  `livingIn_City` INT(9) NULL,
  `base_Country` INT(9) NULL,
  `base_City` INT(9) NULL,
  `profession` INT(9) NULL,
  `aboutme` LONGTEXT NULL,
  `interests` VARCHAR(255) NULL,
  PRIMARY KEY (`upid`),
  UNIQUE INDEX `upid_UNIQUE` (`upid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `matproject`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`interests` (
  `interestsid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`interestsid`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  UNIQUE INDEX `interestsid_UNIQUE` (`interestsid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `matproject`.`profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`profession` (
  `pid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`pid`),
  UNIQUE INDEX `pid_UNIQUE` (`pid` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`gender` (
  `gid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`gid`),
  UNIQUE INDEX `gid_UNIQUE` (`gid` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`cities` (
  `cityid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(2555) NULL,
  `countryid` INT(9) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`cityid`),
  UNIQUE INDEX `cid_UNIQUE` (`cityid` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`countries` (
  `countryid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`countryid`),
  UNIQUE INDEX `countryid_UNIQUE` (`countryid` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`Religion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`Religion` (
  `rid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`rid`),
  UNIQUE INDEX `rid_UNIQUE` (`rid` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`Sect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`Sect` (
  `sid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`sid`),
  UNIQUE INDEX `sid_UNIQUE` (`sid` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`languages` (
  `lid` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `key` VARCHAR(255) NULL,
  PRIMARY KEY (`lid`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`usermeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`usermeta` (
  `umid` INT(9) NOT NULL AUTO_INCREMENT,
  `uid` INT(9) NULL,
  `key` VARCHAR(255) NULL,
  `value` LONGTEXT NULL,
  PRIMARY KEY (`umid`),
  UNIQUE INDEX `umid_UNIQUE` (`umid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`projectoptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`projectoptions` (
  `umid` INT(9) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NULL,
  `value` LONGTEXT NULL,
  PRIMARY KEY (`umid`),
  UNIQUE INDEX `umid_UNIQUE` (`umid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`search_calculator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`search_calculator` (
  `shid` INT(9) NULL,
  `uid` INT(9) NULL,
  `remaining` INT(9) NULL,
  `consumed` INT(9) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matproject`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matproject`.`packages` (
  `pid` INT(9) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL,
  `key` VARCHAR(50) NULL,
  `allowed_searched` INT(9) NULL,
  `price` INT(9) NULL,
  `packageDruation` VARCHAR(50) NULL,
  PRIMARY KEY (`pid`),
  UNIQUE INDEX `pid_UNIQUE` (`pid` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
