<!-- Start Home Page Slider -->
<section id="home">
    <!-- Carousel -->
    <div id="main-slide" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#main-slide" data-slide-to="0" class="active"></li>
            <li data-target="#main-slide" data-slide-to="1"></li>
            <li data-target="#main-slide" data-slide-to="2"></li>
            <li data-target="#main-slide" data-slide-to="3"></li>
            <li data-target="#main-slide" data-slide-to="4"></li>

        </ol>
        <!--/ Indicators end-->

        <!-- Carousel inner -->
        <div class="carousel-inner">

            <div class="item active">
                <img class="img-responsive" src="<?php echo $root."assets/";?>images/slider/bg4.jpg" alt="slider">
                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h2 class="animated7 white">
                            <span>The way of <strong>Success</strong></span>
                        </h2>
                        <h3 class="animated8 white">
                            <span>Why you are waiting</span>
                        </h3>

                        <p class="animated4"><a href="<?php echo $root; ?>register" class="slider btn btn-system btn-large">Sign Up Now</a><a class="animated4 slider btn btn-default " href="<?php echo $root; ?>signin">Login Now</a>
                        </p>
                    </div>
                </div>
            </div>
            <!--/ Carousel item end -->
            <div class="item">
                <img class="img-responsive" src="<?php echo $root."assets/";?>images/slider/bg.jpg" alt="slider">
                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h2 class="animated4">
                            <span><strong>Online Marriage</strong></span>
                        </h2>
                        <h3 class="animated5">
                            <span>Already a member...??</span>
                        </h3>
                        <p class="animated6"><a href="<?php echo $root; ?>signin" class="slider btn btn-system btn-large">Login Now</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item">
                <img class="img-responsive" src="<?php echo $root."assets/";?>images/slider/bg6.jpg" alt="slider">
                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h2 class="animated4">
                            <span><strong>Online Marriage</strong></span>
                        </h2>
                        <h3 class="animated5">
                            <span>Find Your Perfect Match</span>
                        </h3>
                        <p class="animated6"><a href="<?php echo $root; ?>search" class="slider btn btn-system btn-large">Find Now</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item">
                <img class="img-responsive" src="<?php echo $root."assets/";?>images/slider/bg7.jpg" alt="slider">
                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h2 class="animated4">
                            <span><strong>Online Marriage</strong></span>
                        </h2>
                        <h3 class="animated5">
                            <span>We are always Here for You</span>
                        </h3>
                        <p class="animated6"><a href="<?php echo $root; ?>contact" class="slider btn btn-system btn-large">Contact Us</a>
                        </p>
                    </div>
                </div>
            </div>
            <!--/ Carousel item end -->
            <div class="item">
                <img class="img-responsive" src="<?php echo $root."assets/";?>images/slider/bg4.jpg" alt="slider">
                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h2 class="animated4">
                            <span><strong>Online Marriage</strong></span>
                        </h2>
                        <h3 class="animated8 white">
                            <span>Join Us Now...<small>Its free</small></span>
                        </h3>
                        <div class="">
                            <a class="animated4 slider btn btn-system btn-large btn-min-block" href="<?php echo $root; ?>register">Sign Up Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <!--/ Carousel item end -->
        </div>
        <!-- Carousel inner end-->

        <!-- Controls -->
        <a class="left carousel-control" href="#main-slide" data-slide="prev">
            <span><i class="fa fa-angle-left"></i></span>
        </a>
        <a class="right carousel-control" href="#main-slide" data-slide="next">
            <span><i class="fa fa-angle-right"></i></span>
        </a>
    </div>
    <!-- /carousel -->
</section>