<!-- Javascript -->
<script src="<?php echo $root."assets/";?>form/js/jquery-1.11.1.min.js"></script>
<script src="<?php echo $root."assets/";?>form/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $root."assets/";?>form/js/jquery.backstretch.min.js"></script>
<script src="<?php echo $root."assets/";?>form/js/retina-1.1.0.min.js"></script>
<script src="<?php echo $root."assets/";?>form/js/scripts.js"></script>

<!--[if lt IE 10]>
<script src="<?php echo $root."assets/";?>form/js/placeholder.js"></script>
<![endif]-->

</body>

</html>