<footer>
    <div class="container">
        <div class="row footer-widgets">


            <!-- Start Subscribe & Social Links Widget -->
            <div class="col-md-3 col-xs-12">
                <div class="footer-widget mail-subscribe-widget">
                    <h4>Get in touch<span class="head-line"></span></h4>
                    <p>Join our mailing list to stay up to date and get notices about our new releases!</p>
                    <form class="subscribe">
                        <input type="text" placeholder="mail@example.com">
                        <input type="submit" class="btn-system" value="Send">
                    </form>
                </div>
                <div class="footer-widget social-widget">
                    <h4>Follow Us<span class="head-line"></span></h4>
                    <ul class="social-icons">
                        <li>
                            <a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a class="google" href="#"><i class="fa fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a>
                        </li>
                        <li>
                            <a class="linkdin" href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a class="flickr" href="#"><i class="fa fa-flickr"></i></a>
                        </li>
                        <li>
                            <a class="tumblr" href="#"><i class="fa fa-tumblr"></i></a>
                        </li>
                        <li>
                            <a class="instgram" href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a class="vimeo" href="#"><i class="fa fa-vimeo-square"></i></a>
                        </li>
                        <li>
                            <a class="skype" href="#"><i class="fa fa-skype"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- .col-md-3 -->
            <!-- End Subscribe & Social Links Widget -->


            <!-- Start Twitter Widget -->
            <div class="col-md-3 col-xs-12">
                <div class="footer-widget twitter-widget">
                    <h4>Twitter Feed<span class="head-line"></span></h4>
                    <ul>
                        <li>
                            <p><a href="#">@GrayGrids </a> Lorem ipsum dolor et, consectetur adipiscing eli.</p>
                            <span>28 February 2014</span>
                        </li>
                        <li>
                            <p><a href="#">@GrayGrids </a> Lorem ipsum dolor et, consectetur adipiscing eli.An Fusce eleifend aliquet nis application.</p>
                            <span>26 February 2014</span>
                        </li>
                        <li>
                            <p><a href="#">@GrayGrids </a> Lorem ipsum dolor et, consectetur adipiscing eli.</p>
                            <span>28 February 2014</span>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- .col-md-3 -->
            <!-- End Twitter Widget -->


            <!-- Start Flickr Widget -->
            <div class="col-md-3 col-xs-12">
                <div class="footer-widget flickr-widget">
                    <h4>Flicker Feed<span class="head-line"></span></h4>
                    <ul class="flickr-list">
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-01.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-01.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-02.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-02.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-03.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-03.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-04.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-04.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-05.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-05.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-06.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-06.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-07.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-07.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-08.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-08.jpg">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $root."assets/";?>images/flickr-09.jpg" class="lightbox">
                                <img alt="" src="<?php echo $root."assets/";?>images/flickr-09.jpg">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- .col-md-3 -->
            <!-- End Flickr Widget -->


            <!-- Start Contact Widget -->
            <div class="col-md-3 col-xs-12">
                <div class="footer-widget contact-widget">
                    <h4><img src="<?php echo $root."assets/";?>images/footer-margo.png" class="img-responsive" alt="Footer Logo" /></h4>
                    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
                    <ul>
                        <li><span>Phone Number:</span> +01 234 567 890</li>
                        <li><span>Email:</span> company@company.com</li>
                        <li><span>Website:</span> www.yourdomain.com</li>
                    </ul>
                </div>
            </div>
            <!-- .col-md-3 -->
            <!-- End Contact Widget -->


        </div>
        <!-- .row -->

        <!-- Start Copyright -->
        <div class="copyright-section">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2014 Margo - All Rights Reserved <a href="http://graygrids.com">GrayGrids</a> </p>
                </div>
                <!-- .col-md-6 -->
                <div class="col-md-6">
                    <ul class="footer-nav">
                        <li><a href="#">Sitemap</a>
                        </li>
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Contact</a>
                        </li>
                    </ul>
                </div>
                <!-- .col-md-6 -->
            </div>
            <!-- .row -->
        </div>
        <!-- End Copyright -->

    </div>
</footer>
<!-- End Footer Section -->


</div>
<!-- End Full Body Container -->

<!-- Go To Top Link -->
<a href="#" class="back-to-top"><i class="fa fa-angle-up"></i></a>

<div id="loader">
    <div class="spinner">
        <div class="dot1"></div>
        <div class="dot2"></div>
    </div>
</div>

<!-- Style Switcher -->
<div class="switcher-box">
    <a class="open-switcher show-switcher"><i class="fa fa-cog fa-2x"></i></a>
    <h4>Style Switcher</h4>
    <span>12 Predefined Color Skins</span>
    <ul class="colors-list">
        <li>
            <a onClick="setActiveStyleSheet('blue'); return false;" title="Blue" class="blue"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('sky-blue'); return false;" title="Sky Blue" class="sky-blue"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('cyan'); return false;" title="Cyan" class="cyan"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('jade'); return false;" title="Jade" class="jade"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('green'); return false;" title="Green" class="green"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('purple'); return false;" title="Purple" class="purple"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('pink'); return false;" title="Pink" class="pink"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('red'); return false;" title="Red" class="red"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('orange'); return false;" title="Orange" class="orange"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('yellow'); return false;" title="Yellow" class="yellow"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('peach'); return false;" title="Peach" class="peach"></a>
        </li>
        <li>
            <a onClick="setActiveStyleSheet('beige'); return false;" title="Biege" class="beige"></a>
        </li>
    </ul>
    <span>Top Bar Color</span>
    <select id="topbar-style" class="topbar-style">
        <option value="1">Light (Default)</option>
        <option value="2">Dark</option>
        <option value="3">Color</option>
    </select>
    <span>Layout Style</span>
    <select id="layout-style" class="layout-style">
        <option value="1">Wide</option>
        <option value="2">Boxed</option>
    </select>
    <span>Patterns for Boxed Version</span>
    <ul class="bg-list">
        <li>
            <a href="#" class="bg1"></a>
        </li>
        <li>
            <a href="#" class="bg2"></a>
        </li>
        <li>
            <a href="#" class="bg3"></a>
        </li>
        <li>
            <a href="#" class="bg4"></a>
        </li>
        <li>
            <a href="#" class="bg5"></a>
        </li>
        <li>
            <a href="#" class="bg6"></a>
        </li>
        <li>
            <a href="#" class="bg7"></a>
        </li>
        <li>
            <a href="#" class="bg8"></a>
        </li>
        <li>
            <a href="#" class="bg9"></a>
        </li>
        <li>
            <a href="#" class="bg10"></a>
        </li>
        <li>
            <a href="#" class="bg11"></a>
        </li>
        <li>
            <a href="#" class="bg12"></a>
        </li>
        <li>
            <a href="#" class="bg13"></a>
        </li>
        <li>
            <a href="#" class="bg14"></a>
        </li>
    </ul>
</div>

<?php include 'footerfile.inc';?>

</body>

</html>