<!-- Footer Start -->

<!--
<a class="back-top" href="#" id="back-top"> <i class="icon-chevron-up icon-white"> </i> </a> -->

<!-- Javascript =============================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/js/jquery.js"></script>
<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/js/excanvas.js"></script>
<![endif]-->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/js/bootstrap.min.js"></script>
<script type="text/javascript" src='<?php echo $root."assets/";?>update/plugins/jquery-ui/jquery-ui.custom.min.js'></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>

<script type="text/javascript" src="<?php echo $root."assets/";?>update/js/caroufredsel.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/js/plugins.js"></script>

<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/breakpoints/breakpoints.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/dataTables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/prettyPhoto-plugin/js/jquery.prettyPhoto.js"></script>

<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/tagsInput/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/bootstrap-switch/bootstrap-switch.min.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/blockUI/jquery.blockUI.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/pnotify/js/jquery.pnotify.min.js"></script>

<script type="text/javascript" src="<?php echo $root."assets/";?>update/js/theme.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/custom/custom.js"></script>

<!-- Specific Page Scripts Put Here -->

<script type="text/javascript" src='<?php echo $root."assets/";?>update/plugins/jquery-ui/jquery-ui.custom.min.js'></script>


<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.fileupload.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/canvas-to-blob.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<!-- The File Upload processing plugin -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.fileupload-validate.js"></script>
<!-- The File Upload UI plugin -->
<script type="text/javascript" src="<?php echo $root."assets/";?>update/plugins/jquery-file-upload/js/jquery.fileupload-ui.js"></script>


<script type="text/javascript">
    $(window).load(function()
    {
        "use strict";

        $( "#datepicker-normal" ).datepicker({
            dateFormat: 'dd M yy',
            changeMonth: true,
            changeYear: true

        });




    })
</script>
<!-- Specific Page Scripts END -->




<!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information. -->

<script>
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-43329142-3']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>


</body>
</html>