<!doctype html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><html lang="en" class="no-js"> <![endif]-->
<html lang="en">

<head>

    <!-- Basic -->
    <title>Margo | Home</title>

    <!-- Define Charset -->
    <meta charset="utf-8">

    <!-- Responsive Metatag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Page Description and Author -->
    <meta name="description" content="Margo - Responsive HTML5 Template">
    <meta name="author" content="iThemesLab">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php $root = base_url(); ?>

    <!-- Bootstrap CSS  -->

    <link rel="stylesheet" href="<?php echo $root . "assets/"; ?>asset/css/bootstrap.min.css" type="text/css" media="screen">


    <link rel="stylesheet" href="<?php echo $root . "assets/"; ?>css/bootstrap.min.css" type="text/css" media="screen">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/custom.css"  media="screen" />

    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/tab.css"  media="screen" />

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="<?php echo $root."assets/";?>css/font-awesome.min.css" type="text/css" media="screen">

    <!-- Slicknav -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/slicknav.css" media="screen">

    <!-- Margo CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/style.css" media="screen">

    <!-- Responsive CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/responsive.css" media="screen">

    <!-- Css3 Transitions Styles  -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/animate.css" media="screen">

    <!-- Color CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/red.css" title="red" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/jade.css" title="jade" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/green.css" title="green" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/blue.css" title="blue" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/beige.css" title="beige" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/cyan.css" title="cyan" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/orange.css" title="orange" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/peach.css" title="peach" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/pink.css" title="pink" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/purple.css" title="purple" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/sky-blue.css" title="sky-blue" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root."assets/";?>css/colors/yellow.css" title="yellow" media="screen" />


    <!-- Margo JS  -->

    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery-2.2.3.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/tab.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/img.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/img.jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/form.js"></script>



    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.migrate.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/modernizrr.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>asset/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.fitvids.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/nivo-lightbox.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.appear.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/count-to.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.textillate.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.lettering.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.easypiechart.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.parallax.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/mediaelement-and-player.js"></script>
    <script type="text/javascript" src="<?php echo $root."assets/";?>js/jquery.slicknav.js"></script>
    <script src="<?php echo $root."assets/";?>js/pwstrength-bootstrap.min.js" type="text/javascript" charset="utf-8" async defer></script>


    <!--[if IE 8]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->


</head>

<body>