<!-- Start Top Bar -->
<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <!-- Start Contact Info -->
                <ul class="contact-details">
                    <li><a href="#"><i class="fa fa-map-marker"></i>Lahore, Pakistan</a>
                    </li>
                    <li><a href="mailto:info@therightsol.com"><i class="fa fa-envelope-o"></i>info@therightsol.com</a>
                    </li>
                    <li><a href="#"><i class="fa fa-phone"></i> +92 333 4036014</a>
                    </li>
                </ul>
                <!-- End Contact Info -->
            </div>
            <!-- .col-md-6 -->
            <div class="col-md-5">
                <!-- Start Social Links -->
                <ul class="social-list">
                    <li>
                        <a class="facebook itl-tooltip" data-placement="bottom" title="Facebook" href=" https://www.facebook.com/therightsol"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li>
                        <a class="twitter itl-tooltip" data-placement="bottom" title="Twitter" href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                        <a class="google itl-tooltip" data-placement="bottom" title="Google Plus" href="#"><i class="fa fa-google-plus"></i></a>
                    </li>
                    <li>
                        <a class="dribbble itl-tooltip" data-placement="bottom" title="Website" href="http://www.therightsol.com/"><i class="fa fa-dribbble"></i></a>
                    </li>
                    <li>
                        <a class="flickr itl-tooltip" data-placement="bottom" title="Flickr" href="#"><i class="fa fa-flickr"></i></a>
                    </li>
                    <li>
                        <a class="instgram itl-tooltip" data-placement="bottom" title="Instagram" href="#"><i class="fa fa-instagram"></i></a>
                    </li>

                    <li>
                        <a class="skype itl-tooltip" data-placement="bottom" title="Skype" href="https://www.skype.com/vuprojects14"><i class="fa fa-skype"></i></a>
                    </li>
                </ul>
                <!-- End Social Links -->
            </div>
            <!-- .col-md-6 -->
        </div>
        <!-- .row -->
    </div>
    <!-- .container -->
</div>
<!-- .top-bar -->
<!-- End Top Bar -->